name: aidols
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  # provider: ^4.3.2+3
  # font_awesome_flutter: ^8.11.0
  intl: ^0.16.1
  # firebase
  firebase_analytics: ^5.0.11
  firebase_database: ^3.1.5
  firebase_auth: ^0.10.0
  firebase_core: ^0.4.0
  cloud_firestore: ^0.12.5
  firebase_storage: ^3.1.1
  google_fonts: ^1.1.1
  splashscreen: ^1.3.5
  expand_widget: ^1.1.0
  rflutter_alert: ^1.1.0
  flutter_automation: ^1.4.0
  file_picker: ^1.4.3+2
  google_sign_in: ^4.5.9
  fluttertoast: ^7.1.6  
  # flutter_login: ^1.0.14
  # flutter_login:
  #   path: ../aidols/authdesign/
  font_awesome_flutter: ^8.5.0
  provider: ^4.0.2
  transformer_page_view: ^0.1.6
  flushbar: ^1.9.1
  quiver: ^2.0.5
  image_picker: ^0.6.7+21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"